# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf318d748bf29bc1669e4c69d71f0f371edff8ae2fafb87d3fef759ac1b445fc9b740775f5a8a658860febe652d28010cad33cbd31f5905a0abc9a5420fd84c3

test:
  secret_key_base: 238f16e65131ab09ef48ab6597c72d049b178a0ad112fe8bc72a3044ab13749489eb9edf6e93d7a784f6f605339040b1dd983447839bc4aa42ff817d7ae21b6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
